version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        NODE_ENV: $NODE_ENV
        API_PORT: 8000
    ports:
      - 8000:8000
    networks:
      - local
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NODE_ENV: $NODE_ENV
        NEXT_PUBLIC_API_URL: "http://api:8000"
    ports:
      - 3000:3000
    networks:
      - local

networks:
  local:
