# https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration#exercise
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: global-backendconfig
spec:
  timeoutSec: 3600
  sessionAffinity:
    affinityType: "CLIENT_IP"
  connectionDraining:
    drainingTimeoutSec: 3600
